export const READ_DATA_SUCCEES = "READ_DATA_SUCCEES";
export const READ_DATA_FAIL = "READ_DATA_FAIL";
export const READ_DATA_REQUEST = "READ_DATA_REQUEST";
export const READ_DATA_NOT_FOUND = "READ_DATA_NOT_FOUND";